CATEGORIES = {
    "Software Engineering": ["software engineer", "software developer"],
    "Frontend Engineering": ["frontend", "front-end", "react developer"],
    "Backend Engineering": ["backend", "back-end"],
    "Full Stack Engineering": ["full stack", "fullstack"],
    "Mobile Development": ["mobile developer", "ios developer", "android developer"],
    "Data Engineering": ["data engineer"],
    "Data Science": ["data scientist"],
    "Data Analytics": ["data analyst", "analytics engineer"],
    "Machine Learning": ["machine learning", "ml engineer"],
    "Artificial Intelligence": ["artificial intelligence", " ai "],
    "Cybersecurity": ["cybersecurity", "security engineer", "security analyst"],
    "Cloud Security": ["cloud security"],
    "DevOps": ["devops"],
    "Site Reliability Engineering": ["site reliability", "sre"],
    "Platform Engineering": ["platform engineer"],
    "Cloud Engineering": ["cloud engineer"],
    "IT Support": ["it support", "help desk", "helpdesk"],
    "Systems Administration": ["system administrator", "systems administrator", "sysadmin"],
    "Network Engineering": ["network engineer"],
    "Database Engineering": ["database engineer", "dba"],
    "QA / Test Engineering": ["qa engineer", "test engineer", "quality assurance"],
    "Blockchain / Web3": ["blockchain", "web3", "smart contract"],
    "Embedded Systems": ["embedded systems", "firmware engineer"],
    "Solutions Architecture": ["solutions architect"],
    "Technical Program Management": ["technical program manager"],
    "Product Management - Technical": ["technical product manager"],
    "UI/UX - Technology": ["ux designer", "ui designer", "product designer"],
    "Technical Writing": ["technical writer"],
    "Developer Relations": ["developer relations", "developer advocate"],
    "Research / Computer Science": ["computer scientist", "research scientist", "computer science"],
}
